export interface data {
	place: string;
	braille: number;
	openess: number;
	readability: number;
	helpfulness: number;
	avg: number;
	address: string;
	img: string;
}

export const fakeData: Array<data> = [
	{
		place: "Chipotle",
		braille: 5,
		openess: 2,
		readability: 4,
		helpfulness: 5,
		avg: 4,
		address: "15 Brown Ave",
		img: "../../assets/restaurant.jpg",
	},
	{
		place: "Starbucks",
		braille: 1,
		openess: 1,
		readability: 1,
		helpfulness: 5,
		avg: 2,
		address: "34 Northern Ave",
		img: "../../assets/restaurant.jpg",
	},
	{
		place: "Pizza Hut",
		braille: 4,
		openess: 3,
		readability: 4,
		helpfulness: 2,
		avg: 3,
		address: "18 Happy Place",
		img: "../../assets/restaurant.jpg",
	},
	{
		place: "McDonalds",
		braille: 5,
		openess: 5,
		readability: 5,
		helpfulness: 5,
		avg: 5,
		address: "3 Great St",
		img: "../../assets/restaurant.jpg",
	},
	{
		place: "Midtown",
		braille: 4,
		openess: 4,
		readability: 4,
		helpfulness: 4,
		avg: 4,
		address: "44 Lake Ave",
		img: "../../assets/restaurant.jpg",
	},
	{
		place: "Burger King",
		braille: 1,
		openess: 1,
		readability: 1,
		helpfulness: 1,
		avg: 1,
		address: "23 James St",
		img: "../../assets/restaurant.jpg",
	},
	{
		place: "Gio's",
		braille: 5,
		openess: 2,
		readability: 4,
		helpfulness: 5,
		avg: 4,
		address: "8 Bryant Pl",
		img: "../../assets/restaurant.jpg",
	},
	{
		place: "Julio's Chicken",
		braille: 1,
		openess: 1,
		readability: 1,
		helpfulness: 5,
		avg: 2,
		address: "2 Manchester Ave",
		img: "../../assets/restaurant.jpg",
	},
	{
		place: "Andrew's Tea Shop",
		braille: 4,
		openess: 3,
		readability: 4,
		helpfulness: 2,
		avg: 3,
		address: "19 Hogwarts Ave",
		img: "../../assets/restaurant.jpg",
	},
	{
		place: "David's Cookies",
		braille: 5,
		openess: 2,
		readability: 4,
		helpfulness: 5,
		avg: 4,
		address: "10 Sesame St",
		img: "../../assets/restaurant.jpg",
	},
	{
		place: "Alexis's Ale",
		braille: 1,
		openess: 1,
		readability: 1,
		helpfulness: 5,
		avg: 2,
		address: "5 Jones Ave",
		img: "../../assets/restaurant.jpg",
	},
	{
		place: "Eleni's Eggplants",
		braille: 4,
		openess: 3,
		readability: 4,
		helpfulness: 2,
		avg: 3,
		address: "11 Great Pl",
		img: "../../assets/restaurant.jpg",
	},
];
