# Basic dependabot.yml file

version: 2
updates:
  # Enable version updates for yarn (github documentation says to use npm for yarn)
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates on Mondays at 8pm eastern time
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/New_York"
    reviewers:
      - "elenirotsides"
      - "carpenterd777"
      - "aej11a"
      - "jlora23"
    labels:
      - "dependencies"
    # we do not have more than 100 dependencies, so this limit should be good
    open-pull-requests-limit: 100
