name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          expo-token: ${{secrets.EXPO_TOKEN}}

      - name: Install dependencies
        run: yarn

      - name: Build on EAS
        run: |
          eas  build --platform android --profile preview --non-interactive
          # eas build --platform all --profile preview --non-interactive
          # can't run this until Andrew adds his apple account credentials for building
